# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1settings_agent_speak_item_provider_open_ai_model import (
    AgentV1SettingsAgentSpeakItemProviderOpenAiModel,
)
from ..types.agent_v1settings_agent_speak_item_provider_open_ai_voice import (
    AgentV1SettingsAgentSpeakItemProviderOpenAiVoice,
)


class AgentV1SettingsAgentSpeakItemProviderOpenAiParams(typing_extensions.TypedDict):
    model: AgentV1SettingsAgentSpeakItemProviderOpenAiModel
    """
    OpenAI TTS model
    """

    voice: AgentV1SettingsAgentSpeakItemProviderOpenAiVoice
    """
    OpenAI voice
    """
