# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .agent_v1update_speak_speak import AgentV1UpdateSpeakSpeakParams


class AgentV1UpdateSpeakParams(typing_extensions.TypedDict):
    type: typing.Literal["UpdateSpeak"]
    """
    Message type identifier for updating the speak model
    """

    speak: AgentV1UpdateSpeakSpeakParams
    """
    Configuration for the speak model. Optional, defaults to latest deepgram TTS model
    """
