# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1update_speak_type import AgentV1UpdateSpeakType
from .agent_v1update_speak_speak import AgentV1UpdateSpeakSpeakParams


class AgentV1UpdateSpeakParams(typing_extensions.TypedDict):
    type: AgentV1UpdateSpeakType
    """
    Message type identifier for updating the speak model
    """

    speak: AgentV1UpdateSpeakSpeakParams
