# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1settings_agent_speak_one_item_provider_cartesia_model_id import (
    AgentV1SettingsAgentSpeakOneItemProviderCartesiaModelId,
)
from .agent_v1settings_agent_speak_one_item_provider_cartesia_voice import (
    AgentV1SettingsAgentSpeakOneItemProviderCartesiaVoiceParams,
)


class AgentV1SettingsAgentSpeakOneItemProviderCartesiaParams(typing_extensions.TypedDict):
    model_id: AgentV1SettingsAgentSpeakOneItemProviderCartesiaModelId
    """
    Cartesia model ID
    """

    voice: AgentV1SettingsAgentSpeakOneItemProviderCartesiaVoiceParams
    language: typing_extensions.NotRequired[str]
    """
    Cartesia language code
    """
