# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1inject_agent_message_type import AgentV1InjectAgentMessageType


class AgentV1InjectAgentMessageParams(typing_extensions.TypedDict):
    type: AgentV1InjectAgentMessageType
    """
    Message type identifier for injecting an agent message
    """

    message: str
    """
    The statement that the agent should say
    """
