# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .agent_v1settings_agent_context_context import AgentV1SettingsAgentContextContextParams
from .agent_v1settings_agent_context_messages_item import AgentV1SettingsAgentContextMessagesItemParams
from .agent_v1settings_agent_context_listen import AgentV1SettingsAgentContextListenParams
from .agent_v1settings_agent_context_speak import AgentV1SettingsAgentContextSpeakParams
from .agent_v1settings_agent_context_think import AgentV1SettingsAgentContextThinkParams


class AgentV1SettingsAgentContextParams(typing_extensions.TypedDict):
    language: typing_extensions.NotRequired[str]
    """
    Deprecated. Use `listen.provider.language` and `speak.provider.language` fields instead.
    """

    messages: typing_extensions.NotRequired[typing.Sequence[AgentV1SettingsAgentContextMessagesItemParams]]
    """
    Deprecated. Conversation history as a list of messages and function calls.
    """

    context: typing_extensions.NotRequired[AgentV1SettingsAgentContextContextParams]
    """
    Conversation context including the history of messages and function calls
    """

    listen: typing_extensions.NotRequired[AgentV1SettingsAgentContextListenParams]
    think: typing_extensions.NotRequired[AgentV1SettingsAgentContextThinkParams]
    speak: typing_extensions.NotRequired[AgentV1SettingsAgentContextSpeakParams]
    greeting: typing_extensions.NotRequired[str]
    """
    Optional message that agent will speak at the start
    """
