# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1settings_agent_speak_item_provider_aws_polly_engine import (
    AgentV1SettingsAgentSpeakItemProviderAwsPollyEngine,
)
from ..types.agent_v1settings_agent_speak_item_provider_aws_polly_voice import (
    AgentV1SettingsAgentSpeakItemProviderAwsPollyVoice,
)
from .agent_v1settings_agent_speak_item_provider_aws_polly_credentials import (
    AgentV1SettingsAgentSpeakItemProviderAwsPollyCredentialsParams,
)


class AgentV1SettingsAgentSpeakItemProviderAwsPollyParams(typing_extensions.TypedDict):
    voice: AgentV1SettingsAgentSpeakItemProviderAwsPollyVoice
    """
    AWS Polly voice name
    """

    language_code: str
    """
    Language code (e.g., "en-US")
    """

    engine: AgentV1SettingsAgentSpeakItemProviderAwsPollyEngine
    credentials: AgentV1SettingsAgentSpeakItemProviderAwsPollyCredentialsParams
