# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions
from ..types.agent_v1update_speak_speak_provider_aws_polly_engine import AgentV1UpdateSpeakSpeakProviderAwsPollyEngine
from ..types.agent_v1update_speak_speak_provider_aws_polly_voice import AgentV1UpdateSpeakSpeakProviderAwsPollyVoice
from ..types.agent_v1update_speak_speak_provider_cartesia_model_id import AgentV1UpdateSpeakSpeakProviderCartesiaModelId
from ..types.agent_v1update_speak_speak_provider_deepgram_model import AgentV1UpdateSpeakSpeakProviderDeepgramModel
from ..types.agent_v1update_speak_speak_provider_eleven_labs_model_id import (
    AgentV1UpdateSpeakSpeakProviderElevenLabsModelId,
)
from ..types.agent_v1update_speak_speak_provider_open_ai_model import AgentV1UpdateSpeakSpeakProviderOpenAiModel
from ..types.agent_v1update_speak_speak_provider_open_ai_voice import AgentV1UpdateSpeakSpeakProviderOpenAiVoice
from .agent_v1update_speak_speak_provider_aws_polly_credentials import (
    AgentV1UpdateSpeakSpeakProviderAwsPollyCredentialsParams,
)
from .agent_v1update_speak_speak_provider_cartesia_voice import AgentV1UpdateSpeakSpeakProviderCartesiaVoiceParams


class AgentV1UpdateSpeakSpeakProvider_DeepgramParams(typing_extensions.TypedDict):
    type: typing.Literal["deepgram"]
    model: AgentV1UpdateSpeakSpeakProviderDeepgramModel


class AgentV1UpdateSpeakSpeakProvider_ElevenLabsParams(typing_extensions.TypedDict):
    type: typing.Literal["eleven_labs"]
    model_id: AgentV1UpdateSpeakSpeakProviderElevenLabsModelId
    language_code: typing_extensions.NotRequired[str]


class AgentV1UpdateSpeakSpeakProvider_CartesiaParams(typing_extensions.TypedDict):
    type: typing.Literal["cartesia"]
    model_id: AgentV1UpdateSpeakSpeakProviderCartesiaModelId
    voice: AgentV1UpdateSpeakSpeakProviderCartesiaVoiceParams
    language: typing_extensions.NotRequired[str]


class AgentV1UpdateSpeakSpeakProvider_OpenAiParams(typing_extensions.TypedDict):
    type: typing.Literal["open_ai"]
    model: AgentV1UpdateSpeakSpeakProviderOpenAiModel
    voice: AgentV1UpdateSpeakSpeakProviderOpenAiVoice


class AgentV1UpdateSpeakSpeakProvider_AwsPollyParams(typing_extensions.TypedDict):
    type: typing.Literal["aws_polly"]
    voice: AgentV1UpdateSpeakSpeakProviderAwsPollyVoice
    language_code: str
    engine: AgentV1UpdateSpeakSpeakProviderAwsPollyEngine
    credentials: AgentV1UpdateSpeakSpeakProviderAwsPollyCredentialsParams


AgentV1UpdateSpeakSpeakProviderParams = typing.Union[
    AgentV1UpdateSpeakSpeakProvider_DeepgramParams,
    AgentV1UpdateSpeakSpeakProvider_ElevenLabsParams,
    AgentV1UpdateSpeakSpeakProvider_CartesiaParams,
    AgentV1UpdateSpeakSpeakProvider_OpenAiParams,
    AgentV1UpdateSpeakSpeakProvider_AwsPollyParams,
]
