# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1settings_agent_speak_item_provider_eleven_labs_model_id import (
    AgentV1SettingsAgentSpeakItemProviderElevenLabsModelId,
)


class AgentV1SettingsAgentSpeakItemProviderElevenLabsParams(typing_extensions.TypedDict):
    model_id: AgentV1SettingsAgentSpeakItemProviderElevenLabsModelId
    """
    Eleven Labs model ID
    """

    language_code: typing_extensions.NotRequired[str]
    """
    Eleven Labs optional language code
    """
