# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.agent_v1update_speak_speak_provider_deepgram_model import AgentV1UpdateSpeakSpeakProviderDeepgramModel


class AgentV1UpdateSpeakSpeakProviderDeepgramParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[typing.Literal["v1"]]
    """
    The REST API version for the Deepgram text-to-speech API
    """

    model: AgentV1UpdateSpeakSpeakProviderDeepgramModel
    """
    Deepgram TTS model
    """
