# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.agent_v1update_speak_speak_provider_cartesia_model_id import AgentV1UpdateSpeakSpeakProviderCartesiaModelId
from .agent_v1update_speak_speak_provider_cartesia_voice import AgentV1UpdateSpeakSpeakProviderCartesiaVoiceParams


class AgentV1UpdateSpeakSpeakProviderCartesiaParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[typing.Literal["2025-03-17"]]
    """
    The API version header for the Cartesia text-to-speech API
    """

    model_id: AgentV1UpdateSpeakSpeakProviderCartesiaModelId
    """
    Cartesia model ID
    """

    voice: AgentV1UpdateSpeakSpeakProviderCartesiaVoiceParams
    language: typing_extensions.NotRequired[str]
    """
    Cartesia language code
    """
