# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class AgentV1LatencyReportParams(typing_extensions.TypedDict):
    type: typing.Literal["LatencyReport"]
    """
    Message type identifier for the latency report
    """

    ttt_token_latency: typing_extensions.NotRequired[float]
    """
    Time to first token of any type (text, tool call, or thinking), in seconds
    """

    ttt_text_latency: typing_extensions.NotRequired[float]
    """
    Time to first text token from the LLM, in seconds
    """

    ttt_tool_latency: typing_extensions.NotRequired[float]
    """
    Time to first tool-call token from the LLM, in seconds
    """

    ttt_thinking_latency: typing_extensions.NotRequired[float]
    """
    Time to first thinking token from the LLM, in seconds
    """

    tts_latency: typing_extensions.NotRequired[float]
    """
    Text-to-speech: time from first text token to first audio byte, in seconds
    """

    total_latency: typing_extensions.NotRequired[float]
    """
    End-to-end: time from user utterance end to first audio byte, in seconds
    """
