# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1update_speak_speak_provider_aws_polly_engine import AgentV1UpdateSpeakSpeakProviderAwsPollyEngine
from ..types.agent_v1update_speak_speak_provider_aws_polly_voice import AgentV1UpdateSpeakSpeakProviderAwsPollyVoice
from .agent_v1update_speak_speak_provider_aws_polly_credentials import (
    AgentV1UpdateSpeakSpeakProviderAwsPollyCredentialsParams,
)


class AgentV1UpdateSpeakSpeakProviderAwsPollyParams(typing_extensions.TypedDict):
    voice: AgentV1UpdateSpeakSpeakProviderAwsPollyVoice
    """
    AWS Polly voice name
    """

    language: str
    """
    Language code to use, e.g. 'en-US'. Corresponds to the `language_code` parameter in the AWS Polly API
    """

    language_code: typing_extensions.NotRequired[str]
    """
    Use the `language` field instead.
    """

    engine: AgentV1UpdateSpeakSpeakProviderAwsPollyEngine
    credentials: AgentV1UpdateSpeakSpeakProviderAwsPollyCredentialsParams
