# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_v1settings_agent_speak_endpoint import AgentV1SettingsAgentSpeakEndpointParams
from .agent_v1settings_agent_speak_item import AgentV1SettingsAgentSpeakItemParams

AgentV1SettingsAgentSpeakParams = typing.Union[
    AgentV1SettingsAgentSpeakEndpointParams, typing.Sequence[AgentV1SettingsAgentSpeakItemParams]
]
