# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1settings_agent_speak_item_provider_deepgram_model import (
    AgentV1SettingsAgentSpeakItemProviderDeepgramModel,
)


class AgentV1SettingsAgentSpeakItemProviderDeepgramParams(typing_extensions.TypedDict):
    model: AgentV1SettingsAgentSpeakItemProviderDeepgramModel
    """
    Deepgram TTS model
    """
