# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_v1settings_agent_context_context_messages_item_content import (
    AgentV1SettingsAgentContextContextMessagesItemContentParams,
)
from .agent_v1settings_agent_context_context_messages_item_function_calls import (
    AgentV1SettingsAgentContextContextMessagesItemFunctionCallsParams,
)

AgentV1SettingsAgentContextContextMessagesItemParams = typing.Union[
    AgentV1SettingsAgentContextContextMessagesItemContentParams,
    AgentV1SettingsAgentContextContextMessagesItemFunctionCallsParams,
]
