# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1update_speak_speak_endpoint_provider_eleven_labs_model_id import (
    AgentV1UpdateSpeakSpeakEndpointProviderElevenLabsModelId,
)
from ..types.agent_v1update_speak_speak_endpoint_provider_eleven_labs_version import (
    AgentV1UpdateSpeakSpeakEndpointProviderElevenLabsVersion,
)


class AgentV1UpdateSpeakSpeakEndpointProviderElevenLabsParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[AgentV1UpdateSpeakSpeakEndpointProviderElevenLabsVersion]
    """
    The REST API version for the ElevenLabs text-to-speech API
    """

    model_id: AgentV1UpdateSpeakSpeakEndpointProviderElevenLabsModelId
    """
    Eleven Labs model ID
    """

    language: typing_extensions.NotRequired[str]
    """
    Optional language to use, e.g. 'en-US'. Corresponds to the `language_code` parameter in the ElevenLabs API
    """

    language_code: typing_extensions.NotRequired[str]
    """
    Use the `language` field instead.
    """
