# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1agent_thinking_type import AgentV1AgentThinkingType


class AgentV1AgentThinkingParams(typing_extensions.TypedDict):
    type: AgentV1AgentThinkingType
    """
    Message type identifier for agent thinking
    """

    content: str
    """
    The text of the agent's thought process
    """
