# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1update_speak_speak_one_item_provider_cartesia_model_id import (
    AgentV1UpdateSpeakSpeakOneItemProviderCartesiaModelId,
)
from ..types.agent_v1update_speak_speak_one_item_provider_cartesia_version import (
    AgentV1UpdateSpeakSpeakOneItemProviderCartesiaVersion,
)
from .agent_v1update_speak_speak_one_item_provider_cartesia_voice import (
    AgentV1UpdateSpeakSpeakOneItemProviderCartesiaVoiceParams,
)


class AgentV1UpdateSpeakSpeakOneItemProviderCartesiaParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[AgentV1UpdateSpeakSpeakOneItemProviderCartesiaVersion]
    """
    The API version header for the Cartesia text-to-speech API
    """

    model_id: AgentV1UpdateSpeakSpeakOneItemProviderCartesiaModelId
    """
    Cartesia model ID
    """

    voice: AgentV1UpdateSpeakSpeakOneItemProviderCartesiaVoiceParams
    language: typing_extensions.NotRequired[str]
    """
    Cartesia language code
    """
