# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class AgentV1SettingsAgentListenProviderParams(typing_extensions.TypedDict):
    type: typing.Literal["deepgram"]
    """
    Provider type for speech-to-text
    """

    model: typing_extensions.NotRequired[str]
    """
    Model to use for speech to text
    """

    keyterms: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Prompt key-term recognition (nova-3 'en' only)
    """

    smart_format: typing_extensions.NotRequired[bool]
    """
    Applies smart formatting to improve transcript readability (Deepgram providers only)
    """
