# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class AgentV1SettingsAppliedParams(typing_extensions.TypedDict):
    type: typing.Literal["SettingsApplied"]
    """
    Message type identifier for settings applied confirmation
    """
