# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1update_speak_speak_endpoint_provider_cartesia_model_id import (
    AgentV1UpdateSpeakSpeakEndpointProviderCartesiaModelId,
)
from ..types.agent_v1update_speak_speak_endpoint_provider_cartesia_version import (
    AgentV1UpdateSpeakSpeakEndpointProviderCartesiaVersion,
)
from .agent_v1update_speak_speak_endpoint_provider_cartesia_voice import (
    AgentV1UpdateSpeakSpeakEndpointProviderCartesiaVoiceParams,
)


class AgentV1UpdateSpeakSpeakEndpointProviderCartesiaParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[AgentV1UpdateSpeakSpeakEndpointProviderCartesiaVersion]
    """
    The API version header for the Cartesia text-to-speech API
    """

    model_id: AgentV1UpdateSpeakSpeakEndpointProviderCartesiaModelId
    """
    Cartesia model ID
    """

    voice: AgentV1UpdateSpeakSpeakEndpointProviderCartesiaVoiceParams
    language: typing_extensions.NotRequired[str]
    """
    Cartesia language code
    """
