# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .agent_v1update_listen_listen_provider import AgentV1UpdateListenListenProviderParams


class AgentV1UpdateListenListenParams(typing_extensions.TypedDict):
    """
    Listen configuration to update. Contains a provider object with the same schema as Settings. The model and language can be changed mid-session. Keyterms can only be updated mid-session for Flux models.
    """

    provider: AgentV1UpdateListenListenProviderParams
