# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1update_speak_speak_one_item_provider_open_ai_model import (
    AgentV1UpdateSpeakSpeakOneItemProviderOpenAiModel,
)
from ..types.agent_v1update_speak_speak_one_item_provider_open_ai_version import (
    AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVersion,
)
from ..types.agent_v1update_speak_speak_one_item_provider_open_ai_voice import (
    AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVoice,
)


class AgentV1UpdateSpeakSpeakOneItemProviderOpenAiParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVersion]
    """
    The REST API version for the OpenAI text-to-speech API
    """

    model: AgentV1UpdateSpeakSpeakOneItemProviderOpenAiModel
    """
    OpenAI TTS model
    """

    voice: AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVoice
    """
    OpenAI voice
    """
