# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1settings_agent_speak_endpoint_provider_open_ai_model import (
    AgentV1SettingsAgentSpeakEndpointProviderOpenAiModel,
)
from ..types.agent_v1settings_agent_speak_endpoint_provider_open_ai_voice import (
    AgentV1SettingsAgentSpeakEndpointProviderOpenAiVoice,
)


class AgentV1SettingsAgentSpeakEndpointProviderOpenAiParams(typing_extensions.TypedDict):
    model: AgentV1SettingsAgentSpeakEndpointProviderOpenAiModel
    """
    OpenAI TTS model
    """

    voice: AgentV1SettingsAgentSpeakEndpointProviderOpenAiVoice
    """
    OpenAI voice
    """
