# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_v1settings_agent_speak_endpoint_provider_cartesia_model_id import (
    AgentV1SettingsAgentSpeakEndpointProviderCartesiaModelId,
)
from .agent_v1settings_agent_speak_endpoint_provider_cartesia_voice import (
    AgentV1SettingsAgentSpeakEndpointProviderCartesiaVoiceParams,
)


class AgentV1SettingsAgentSpeakEndpointProviderCartesiaParams(typing_extensions.TypedDict):
    model_id: AgentV1SettingsAgentSpeakEndpointProviderCartesiaModelId
    """
    Cartesia model ID
    """

    voice: AgentV1SettingsAgentSpeakEndpointProviderCartesiaVoiceParams
    language: typing_extensions.NotRequired[str]
    """
    Cartesia language code
    """
