# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.agent_v1settings_agent_think_provider_anthropic_model import (
    AgentV1SettingsAgentThinkProviderAnthropicModel,
)


class AnthropicParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[typing.Literal["v1"]]
    """
    The REST API version for the Anthropic Messages API
    """

    model: AgentV1SettingsAgentThinkProviderAnthropicModel
    """
    Anthropic model to use
    """

    temperature: typing_extensions.NotRequired[float]
    """
    Anthropic temperature (0-1)
    """
