# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.agent_v1settings_agent_speak_one_item_provider_cartesia_model_id import (
    AgentV1SettingsAgentSpeakOneItemProviderCartesiaModelId,
)
from .agent_v1settings_agent_speak_one_item_provider_cartesia_voice import (
    AgentV1SettingsAgentSpeakOneItemProviderCartesiaVoiceParams,
)


class CartesiaParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[typing.Literal["2025-03-17"]]
    """
    The API version header for the Cartesia text-to-speech API
    """

    model_id: AgentV1SettingsAgentSpeakOneItemProviderCartesiaModelId
    """
    Cartesia model ID
    """

    voice: AgentV1SettingsAgentSpeakOneItemProviderCartesiaVoiceParams
    language: typing_extensions.NotRequired[str]
    """
    Cartesia language code
    """
