# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.agent_v1settings_agent_think_provider_google_model import AgentV1SettingsAgentThinkProviderGoogleModel


class GoogleParams(typing_extensions.TypedDict):
    version: typing_extensions.NotRequired[typing.Literal["v1beta"]]
    """
    The REST API version for the Google generative language API
    """

    model: AgentV1SettingsAgentThinkProviderGoogleModel
    """
    Google model to use
    """

    temperature: typing_extensions.NotRequired[float]
    """
    Google temperature (0-2)
    """
