# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .listen_v2close_stream import ListenV2CloseStream
    from .listen_v2close_stream_type import ListenV2CloseStreamType
    from .listen_v2connected import ListenV2Connected
    from .listen_v2fatal_error import ListenV2FatalError
    from .listen_v2turn_info import ListenV2TurnInfo
    from .listen_v2turn_info_event import ListenV2TurnInfoEvent
    from .listen_v2turn_info_words_item import ListenV2TurnInfoWordsItem
_dynamic_imports: typing.Dict[str, str] = {
    "ListenV2CloseStream": ".listen_v2close_stream",
    "ListenV2CloseStreamType": ".listen_v2close_stream_type",
    "ListenV2Connected": ".listen_v2connected",
    "ListenV2FatalError": ".listen_v2fatal_error",
    "ListenV2TurnInfo": ".listen_v2turn_info",
    "ListenV2TurnInfoEvent": ".listen_v2turn_info_event",
    "ListenV2TurnInfoWordsItem": ".listen_v2turn_info_words_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListenV2CloseStream",
    "ListenV2CloseStreamType",
    "ListenV2Connected",
    "ListenV2FatalError",
    "ListenV2TurnInfo",
    "ListenV2TurnInfoEvent",
    "ListenV2TurnInfoWordsItem",
]
