# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ._dict_compat import ListenV2ResponseDictCompatModel


class ListenV2TurnInfoWordsItem(ListenV2ResponseDictCompatModel):
    word: str = pydantic.Field()
    """
    The individual punctuated, properly-cased word from the transcript
    """

    confidence: float = pydantic.Field()
    """
    Confidence that this word was transcribed correctly
    """

    start: typing.Optional[float] = pydantic.Field(default=None)
    """
    The start time of the word
    """

    end: typing.Optional[float] = pydantic.Field(default=None)
    """
    The end time of the word
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
