# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from ....types.listen_v2keyterm import ListenV2Keyterm
from .listen_v2configure_success_thresholds import ListenV2ConfigureSuccessThresholds


class ListenV2ConfigureSuccess(UncheckedBaseModel):
    type: typing.Literal["ConfigureSuccess"] = pydantic.Field(default="ConfigureSuccess")
    """
    Message type identifier
    """

    request_id: str = pydantic.Field()
    """
    The unique identifier of the request
    """

    thresholds: ListenV2ConfigureSuccessThresholds = pydantic.Field()
    """
    Updates each parameter, if it is supplied. If a particular threshold parameter 
    is not supplied, the configuration continues using the currently configured value.
    """

    keyterms: ListenV2Keyterm
    sequence_id: float = pydantic.Field()
    """
    Starts at `0` and increments for each message the server sends
    to the client.  This includes messages of other types, like
    `TurnInfo` messages.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
