# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent_v1agent_thinking import AgentV1AgentThinking
    from .agent_v1conversation_text import AgentV1ConversationText
    from .agent_v1conversation_text_role import AgentV1ConversationTextRole
    from .agent_v1inject_agent_message import AgentV1InjectAgentMessage
    from .agent_v1inject_user_message import AgentV1InjectUserMessage
    from .agent_v1injection_refused import AgentV1InjectionRefused
    from .agent_v1keep_alive import AgentV1KeepAlive
    from .agent_v1receive_function_call_response import AgentV1ReceiveFunctionCallResponse
    from .agent_v1send_function_call_response import AgentV1SendFunctionCallResponse
    from .agent_v1settings_applied import AgentV1SettingsApplied
    from .agent_v1update_prompt import AgentV1UpdatePrompt
    from .agent_v1update_speak import AgentV1UpdateSpeak
    from .agent_v1update_speak_speak import AgentV1UpdateSpeakSpeak
    from .agent_v1update_speak_speak_endpoint import AgentV1UpdateSpeakSpeakEndpoint
    from .agent_v1update_speak_speak_provider import (
        AgentV1UpdateSpeakSpeakProvider,
        AgentV1UpdateSpeakSpeakProvider_AwsPolly,
        AgentV1UpdateSpeakSpeakProvider_Cartesia,
        AgentV1UpdateSpeakSpeakProvider_Deepgram,
        AgentV1UpdateSpeakSpeakProvider_ElevenLabs,
        AgentV1UpdateSpeakSpeakProvider_OpenAi,
    )
    from .agent_v1update_speak_speak_provider_aws_polly import AgentV1UpdateSpeakSpeakProviderAwsPolly
    from .agent_v1update_speak_speak_provider_aws_polly_credentials import (
        AgentV1UpdateSpeakSpeakProviderAwsPollyCredentials,
    )
    from .agent_v1update_speak_speak_provider_aws_polly_credentials_type import (
        AgentV1UpdateSpeakSpeakProviderAwsPollyCredentialsType,
    )
    from .agent_v1update_speak_speak_provider_aws_polly_engine import AgentV1UpdateSpeakSpeakProviderAwsPollyEngine
    from .agent_v1update_speak_speak_provider_aws_polly_voice import AgentV1UpdateSpeakSpeakProviderAwsPollyVoice
    from .agent_v1update_speak_speak_provider_cartesia import AgentV1UpdateSpeakSpeakProviderCartesia
    from .agent_v1update_speak_speak_provider_cartesia_model_id import AgentV1UpdateSpeakSpeakProviderCartesiaModelId
    from .agent_v1update_speak_speak_provider_cartesia_voice import AgentV1UpdateSpeakSpeakProviderCartesiaVoice
    from .agent_v1update_speak_speak_provider_deepgram import AgentV1UpdateSpeakSpeakProviderDeepgram
    from .agent_v1update_speak_speak_provider_deepgram_model import AgentV1UpdateSpeakSpeakProviderDeepgramModel
    from .agent_v1update_speak_speak_provider_eleven_labs import AgentV1UpdateSpeakSpeakProviderElevenLabs
    from .agent_v1update_speak_speak_provider_eleven_labs_model_id import (
        AgentV1UpdateSpeakSpeakProviderElevenLabsModelId,
    )
    from .agent_v1update_speak_speak_provider_open_ai import AgentV1UpdateSpeakSpeakProviderOpenAi
    from .agent_v1update_speak_speak_provider_open_ai_model import AgentV1UpdateSpeakSpeakProviderOpenAiModel
    from .agent_v1update_speak_speak_provider_open_ai_voice import AgentV1UpdateSpeakSpeakProviderOpenAiVoice
    from .agent_v1user_started_speaking import AgentV1UserStartedSpeaking
    from .agent_v1welcome import AgentV1Welcome
_dynamic_imports: typing.Dict[str, str] = {
    "AgentV1AgentThinking": ".agent_v1agent_thinking",
    "AgentV1ConversationText": ".agent_v1conversation_text",
    "AgentV1ConversationTextRole": ".agent_v1conversation_text_role",
    "AgentV1InjectAgentMessage": ".agent_v1inject_agent_message",
    "AgentV1InjectUserMessage": ".agent_v1inject_user_message",
    "AgentV1InjectionRefused": ".agent_v1injection_refused",
    "AgentV1KeepAlive": ".agent_v1keep_alive",
    "AgentV1ReceiveFunctionCallResponse": ".agent_v1receive_function_call_response",
    "AgentV1SendFunctionCallResponse": ".agent_v1send_function_call_response",
    "AgentV1SettingsApplied": ".agent_v1settings_applied",
    "AgentV1UpdatePrompt": ".agent_v1update_prompt",
    "AgentV1UpdateSpeak": ".agent_v1update_speak",
    "AgentV1UpdateSpeakSpeak": ".agent_v1update_speak_speak",
    "AgentV1UpdateSpeakSpeakEndpoint": ".agent_v1update_speak_speak_endpoint",
    "AgentV1UpdateSpeakSpeakProvider": ".agent_v1update_speak_speak_provider",
    "AgentV1UpdateSpeakSpeakProviderAwsPolly": ".agent_v1update_speak_speak_provider_aws_polly",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyCredentials": ".agent_v1update_speak_speak_provider_aws_polly_credentials",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyCredentialsType": ".agent_v1update_speak_speak_provider_aws_polly_credentials_type",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyEngine": ".agent_v1update_speak_speak_provider_aws_polly_engine",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyVoice": ".agent_v1update_speak_speak_provider_aws_polly_voice",
    "AgentV1UpdateSpeakSpeakProviderCartesia": ".agent_v1update_speak_speak_provider_cartesia",
    "AgentV1UpdateSpeakSpeakProviderCartesiaModelId": ".agent_v1update_speak_speak_provider_cartesia_model_id",
    "AgentV1UpdateSpeakSpeakProviderCartesiaVoice": ".agent_v1update_speak_speak_provider_cartesia_voice",
    "AgentV1UpdateSpeakSpeakProviderDeepgram": ".agent_v1update_speak_speak_provider_deepgram",
    "AgentV1UpdateSpeakSpeakProviderDeepgramModel": ".agent_v1update_speak_speak_provider_deepgram_model",
    "AgentV1UpdateSpeakSpeakProviderElevenLabs": ".agent_v1update_speak_speak_provider_eleven_labs",
    "AgentV1UpdateSpeakSpeakProviderElevenLabsModelId": ".agent_v1update_speak_speak_provider_eleven_labs_model_id",
    "AgentV1UpdateSpeakSpeakProviderOpenAi": ".agent_v1update_speak_speak_provider_open_ai",
    "AgentV1UpdateSpeakSpeakProviderOpenAiModel": ".agent_v1update_speak_speak_provider_open_ai_model",
    "AgentV1UpdateSpeakSpeakProviderOpenAiVoice": ".agent_v1update_speak_speak_provider_open_ai_voice",
    "AgentV1UpdateSpeakSpeakProvider_AwsPolly": ".agent_v1update_speak_speak_provider",
    "AgentV1UpdateSpeakSpeakProvider_Cartesia": ".agent_v1update_speak_speak_provider",
    "AgentV1UpdateSpeakSpeakProvider_Deepgram": ".agent_v1update_speak_speak_provider",
    "AgentV1UpdateSpeakSpeakProvider_ElevenLabs": ".agent_v1update_speak_speak_provider",
    "AgentV1UpdateSpeakSpeakProvider_OpenAi": ".agent_v1update_speak_speak_provider",
    "AgentV1UserStartedSpeaking": ".agent_v1user_started_speaking",
    "AgentV1Welcome": ".agent_v1welcome",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentV1AgentThinking",
    "AgentV1ConversationText",
    "AgentV1ConversationTextRole",
    "AgentV1InjectAgentMessage",
    "AgentV1InjectUserMessage",
    "AgentV1InjectionRefused",
    "AgentV1KeepAlive",
    "AgentV1ReceiveFunctionCallResponse",
    "AgentV1SendFunctionCallResponse",
    "AgentV1SettingsApplied",
    "AgentV1UpdatePrompt",
    "AgentV1UpdateSpeak",
    "AgentV1UpdateSpeakSpeak",
    "AgentV1UpdateSpeakSpeakEndpoint",
    "AgentV1UpdateSpeakSpeakProvider",
    "AgentV1UpdateSpeakSpeakProviderAwsPolly",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyCredentials",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyCredentialsType",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyEngine",
    "AgentV1UpdateSpeakSpeakProviderAwsPollyVoice",
    "AgentV1UpdateSpeakSpeakProviderCartesia",
    "AgentV1UpdateSpeakSpeakProviderCartesiaModelId",
    "AgentV1UpdateSpeakSpeakProviderCartesiaVoice",
    "AgentV1UpdateSpeakSpeakProviderDeepgram",
    "AgentV1UpdateSpeakSpeakProviderDeepgramModel",
    "AgentV1UpdateSpeakSpeakProviderElevenLabs",
    "AgentV1UpdateSpeakSpeakProviderElevenLabsModelId",
    "AgentV1UpdateSpeakSpeakProviderOpenAi",
    "AgentV1UpdateSpeakSpeakProviderOpenAiModel",
    "AgentV1UpdateSpeakSpeakProviderOpenAiVoice",
    "AgentV1UpdateSpeakSpeakProvider_AwsPolly",
    "AgentV1UpdateSpeakSpeakProvider_Cartesia",
    "AgentV1UpdateSpeakSpeakProvider_Deepgram",
    "AgentV1UpdateSpeakSpeakProvider_ElevenLabs",
    "AgentV1UpdateSpeakSpeakProvider_OpenAi",
    "AgentV1UserStartedSpeaking",
    "AgentV1Welcome",
]
