# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_v1settings_agent_speak_endpoint_provider_aws_polly_credentials import (
    AgentV1SettingsAgentSpeakEndpointProviderAwsPollyCredentials,
)
from .agent_v1settings_agent_speak_endpoint_provider_aws_polly_engine import (
    AgentV1SettingsAgentSpeakEndpointProviderAwsPollyEngine,
)
from .agent_v1settings_agent_speak_endpoint_provider_aws_polly_voice import (
    AgentV1SettingsAgentSpeakEndpointProviderAwsPollyVoice,
)


class AgentV1SettingsAgentSpeakEndpointProviderAwsPolly(UniversalBaseModel):
    voice: AgentV1SettingsAgentSpeakEndpointProviderAwsPollyVoice = pydantic.Field()
    """
    AWS Polly voice name
    """

    language: str = pydantic.Field()
    """
    Language to use, e.g. 'en-US'. Corresponds to the `language_code` parameter in the AWS Polly API
    """

    language_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Use the `language` field instead.
    """

    engine: AgentV1SettingsAgentSpeakEndpointProviderAwsPollyEngine
    credentials: AgentV1SettingsAgentSpeakEndpointProviderAwsPollyCredentials

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
