# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentV1Error(UniversalBaseModel):
    type: typing.Literal["Error"] = pydantic.Field(default="Error")
    """
    Message type identifier for error responses
    """

    description: str = pydantic.Field()
    """
    A description of what went wrong
    """

    code: str = pydantic.Field()
    """
    Error code identifying the type of error
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
