# This file was auto-generated by Fern from our API Definition.

import typing

AgentV1SettingsAgentThinkProviderThreeModel = typing.Union[
    typing.Literal["gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-2.5-flash"], typing.Any
]
