# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .agent_v1update_speak_speak_endpoint_provider_aws_polly_credentials import (
    AgentV1UpdateSpeakSpeakEndpointProviderAwsPollyCredentials,
)
from .agent_v1update_speak_speak_endpoint_provider_aws_polly_engine import (
    AgentV1UpdateSpeakSpeakEndpointProviderAwsPollyEngine,
)
from .agent_v1update_speak_speak_endpoint_provider_aws_polly_voice import (
    AgentV1UpdateSpeakSpeakEndpointProviderAwsPollyVoice,
)


class AgentV1UpdateSpeakSpeakEndpointProviderAwsPolly(UncheckedBaseModel):
    voice: AgentV1UpdateSpeakSpeakEndpointProviderAwsPollyVoice = pydantic.Field()
    """
    AWS Polly voice name
    """

    language: str = pydantic.Field()
    """
    Language code to use, e.g. 'en-US'. Corresponds to the `language_code` parameter in the AWS Polly API
    """

    language_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Use the `language` field instead.
    """

    engine: AgentV1UpdateSpeakSpeakEndpointProviderAwsPollyEngine
    credentials: AgentV1UpdateSpeakSpeakEndpointProviderAwsPollyCredentials

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
