# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_v1update_speak_speak_endpoint import AgentV1UpdateSpeakSpeakEndpoint
from .agent_v1update_speak_speak_provider import AgentV1UpdateSpeakSpeakProvider


class AgentV1UpdateSpeakSpeak(UniversalBaseModel):
    """
    Configuration for the speak model. Optional, defaults to latest deepgram TTS model
    """

    provider: AgentV1UpdateSpeakSpeakProvider
    endpoint: typing.Optional[AgentV1UpdateSpeakSpeakEndpoint] = pydantic.Field(default=None)
    """
    Optional if provider is Deepgram. Required for non-Deepgram TTS providers.
    When present, must include url field and headers object. Valid schemes are https and wss with wss only supported for Eleven Labs.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
