# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_v1settings_agent_speak_endpoint_provider_aws_polly_credentials import (
    AgentV1SettingsAgentSpeakEndpointProviderAwsPollyCredentials,
)
from .agent_v1settings_agent_speak_endpoint_provider_aws_polly_engine import (
    AgentV1SettingsAgentSpeakEndpointProviderAwsPollyEngine,
)
from .agent_v1settings_agent_speak_endpoint_provider_aws_polly_voice import (
    AgentV1SettingsAgentSpeakEndpointProviderAwsPollyVoice,
)
from .agent_v1settings_agent_speak_endpoint_provider_cartesia_model_id import (
    AgentV1SettingsAgentSpeakEndpointProviderCartesiaModelId,
)
from .agent_v1settings_agent_speak_endpoint_provider_cartesia_voice import (
    AgentV1SettingsAgentSpeakEndpointProviderCartesiaVoice,
)
from .agent_v1settings_agent_speak_endpoint_provider_deepgram_model import (
    AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel,
)
from .agent_v1settings_agent_speak_endpoint_provider_eleven_labs_model_id import (
    AgentV1SettingsAgentSpeakEndpointProviderElevenLabsModelId,
)
from .agent_v1settings_agent_speak_endpoint_provider_open_ai_model import (
    AgentV1SettingsAgentSpeakEndpointProviderOpenAiModel,
)
from .agent_v1settings_agent_speak_endpoint_provider_open_ai_voice import (
    AgentV1SettingsAgentSpeakEndpointProviderOpenAiVoice,
)


class AgentV1SettingsAgentSpeakEndpointProvider_Deepgram(UniversalBaseModel):
    type: typing.Literal["deepgram"] = "deepgram"
    model: AgentV1SettingsAgentSpeakEndpointProviderDeepgramModel

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentV1SettingsAgentSpeakEndpointProvider_ElevenLabs(UniversalBaseModel):
    type: typing.Literal["eleven_labs"] = "eleven_labs"
    model_id: AgentV1SettingsAgentSpeakEndpointProviderElevenLabsModelId
    language_code: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentV1SettingsAgentSpeakEndpointProvider_Cartesia(UniversalBaseModel):
    type: typing.Literal["cartesia"] = "cartesia"
    model_id: AgentV1SettingsAgentSpeakEndpointProviderCartesiaModelId
    voice: AgentV1SettingsAgentSpeakEndpointProviderCartesiaVoice
    language: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentV1SettingsAgentSpeakEndpointProvider_OpenAi(UniversalBaseModel):
    type: typing.Literal["open_ai"] = "open_ai"
    model: AgentV1SettingsAgentSpeakEndpointProviderOpenAiModel
    voice: AgentV1SettingsAgentSpeakEndpointProviderOpenAiVoice

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentV1SettingsAgentSpeakEndpointProvider_AwsPolly(UniversalBaseModel):
    type: typing.Literal["aws_polly"] = "aws_polly"
    voice: AgentV1SettingsAgentSpeakEndpointProviderAwsPollyVoice
    language_code: str
    engine: AgentV1SettingsAgentSpeakEndpointProviderAwsPollyEngine
    credentials: AgentV1SettingsAgentSpeakEndpointProviderAwsPollyCredentials

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


AgentV1SettingsAgentSpeakEndpointProvider = typing.Union[
    AgentV1SettingsAgentSpeakEndpointProvider_Deepgram,
    AgentV1SettingsAgentSpeakEndpointProvider_ElevenLabs,
    AgentV1SettingsAgentSpeakEndpointProvider_Cartesia,
    AgentV1SettingsAgentSpeakEndpointProvider_OpenAi,
    AgentV1SettingsAgentSpeakEndpointProvider_AwsPolly,
]
