# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .agent_v1update_speak_speak_one_item_provider_open_ai_model import (
    AgentV1UpdateSpeakSpeakOneItemProviderOpenAiModel,
)
from .agent_v1update_speak_speak_one_item_provider_open_ai_version import (
    AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVersion,
)
from .agent_v1update_speak_speak_one_item_provider_open_ai_voice import (
    AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVoice,
)


class AgentV1UpdateSpeakSpeakOneItemProviderOpenAi(UncheckedBaseModel):
    version: typing.Optional[AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVersion] = pydantic.Field(default=None)
    """
    The REST API version for the OpenAI text-to-speech API
    """

    model: AgentV1UpdateSpeakSpeakOneItemProviderOpenAiModel = pydantic.Field()
    """
    OpenAI TTS model
    """

    voice: AgentV1UpdateSpeakSpeakOneItemProviderOpenAiVoice = pydantic.Field()
    """
    OpenAI voice
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
