# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from ....types.deepgram_listen_provider_v2language_hint import DeepgramListenProviderV2LanguageHint


class AgentV1SettingsAgentContextListenProvider_V1(UncheckedBaseModel):
    version: typing.Literal["v1"] = "v1"
    type: typing.Literal["deepgram"] = "deepgram"
    model: typing.Optional[str] = None
    language: typing.Optional[str] = None
    keyterms: typing.Optional[typing.List[str]] = None
    smart_format: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AgentV1SettingsAgentContextListenProvider_V2(UncheckedBaseModel):
    version: typing.Literal["v2"] = "v2"
    type: typing.Literal["deepgram"] = "deepgram"
    model: str
    language_hint: typing.Optional[DeepgramListenProviderV2LanguageHint] = None
    keyterms: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


AgentV1SettingsAgentContextListenProvider = typing_extensions.Annotated[
    typing.Union[AgentV1SettingsAgentContextListenProvider_V1, AgentV1SettingsAgentContextListenProvider_V2],
    UnionMetadata(discriminant="version"),
]
