# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .agent_v1history_function_calls_function_calls_item import AgentV1HistoryFunctionCallsFunctionCallsItem


class AgentV1HistoryFunctionCalls(UncheckedBaseModel):
    """
    Client-side or server-side function call request and response as part of the conversation history
    """

    type: typing.Literal["History"] = "History"
    function_calls: typing.List[AgentV1HistoryFunctionCallsFunctionCallsItem] = pydantic.Field()
    """
    List of function call objects
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
