# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel


class AgentV1LatencyReport(UncheckedBaseModel):
    type: typing.Literal["LatencyReport"] = pydantic.Field(default="LatencyReport")
    """
    Message type identifier for the latency report
    """

    ttt_token_latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    Time to first token of any type (text, tool call, or thinking), in seconds
    """

    ttt_text_latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    Time to first text token from the LLM, in seconds
    """

    ttt_tool_latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    Time to first tool-call token from the LLM, in seconds
    """

    ttt_thinking_latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    Time to first thinking token from the LLM, in seconds
    """

    tts_latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    Text-to-speech: time from first text token to first audio byte, in seconds
    """

    total_latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    End-to-end: time from user utterance end to first audio byte, in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
