# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .agent_v1agent_audio_done_type import AgentV1AgentAudioDoneType


class AgentV1AgentAudioDone(UncheckedBaseModel):
    type: AgentV1AgentAudioDoneType = pydantic.Field()
    """
    Message type identifier indicating the agent has finished sending audio
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
