# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .agent_v1update_listen_listen import AgentV1UpdateListenListen


class AgentV1UpdateListen(UncheckedBaseModel):
    type: typing.Literal["UpdateListen"] = pydantic.Field(default="UpdateListen")
    """
    Message type identifier for updating the listen configuration
    """

    listen: AgentV1UpdateListenListen = pydantic.Field()
    """
    Listen configuration to update. Contains a provider object with the same schema as Settings. The provider identity (type, version, model) is required and must match the current session.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
