# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_v1settings_agent_speak_one_item_provider_aws_polly_credentials_type import (
    AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType,
)


class AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentials(UniversalBaseModel):
    type: AgentV1SettingsAgentSpeakOneItemProviderAwsPollyCredentialsType
    region: str
    access_key_id: str
    secret_access_key: str
    session_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Required for STS only
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
