# This file was auto-generated by Fern from our API Definition.

from .conversation_history_message_role import ConversationHistoryMessageRole

AgentV1HistoryContentRole = ConversationHistoryMessageRole
