# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentV1UpdatePrompt(UniversalBaseModel):
    type: typing.Literal["UpdatePrompt"] = pydantic.Field(default="UpdatePrompt")
    """
    Message type identifier for prompt update request
    """

    prompt: str = pydantic.Field()
    """
    The new system prompt to be used by the agent
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
