# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel


class AgentV1InjectionRefused(UncheckedBaseModel):
    type: typing.Literal["InjectionRefused"] = pydantic.Field(default="InjectionRefused")
    """
    Message type identifier for injection refused
    """

    message: str = pydantic.Field()
    """
    Details about why the injection was refused
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
