# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_v1update_speak_speak_provider_cartesia_model_id import AgentV1UpdateSpeakSpeakProviderCartesiaModelId
from .agent_v1update_speak_speak_provider_cartesia_voice import AgentV1UpdateSpeakSpeakProviderCartesiaVoice


class AgentV1UpdateSpeakSpeakProviderCartesia(UniversalBaseModel):
    model_id: AgentV1UpdateSpeakSpeakProviderCartesiaModelId = pydantic.Field()
    """
    Cartesia model ID
    """

    voice: AgentV1UpdateSpeakSpeakProviderCartesiaVoice
    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cartesia language code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
