# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_v1settings_agent_think_provider_zero_model import AgentV1SettingsAgentThinkProviderZeroModel


class AgentV1SettingsAgentThinkProviderZero(UniversalBaseModel):
    type: typing.Optional[typing.Literal["open_ai"]] = None
    model: typing.Optional[AgentV1SettingsAgentThinkProviderZeroModel] = pydantic.Field(default=None)
    """
    OpenAI model to use
    """

    temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    OpenAI temperature (0-2)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
