# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_v1settings_agent_think_provider_google_model import AgentV1SettingsAgentThinkProviderGoogleModel


class Google(UniversalBaseModel):
    version: typing.Optional[typing.Literal["v1beta"]] = pydantic.Field(default=None)
    """
    The REST API version for the Google generative language API
    """

    model: AgentV1SettingsAgentThinkProviderGoogleModel = pydantic.Field()
    """
    Google model to use
    """

    temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    Google temperature (0-2)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
