# Agent V1 Audio Chunk Event - protected from auto-generation

# This represents binary audio data received from the Voice Agent WebSocket
# The actual data is bytes, but we define this as a type alias for clarity
AgentV1AudioChunkEvent = bytes
"""
Raw binary audio data generated by Deepgram's Voice Agent API.
Content-Type: application/octet-stream
"""
