runtime: python
entrypoint: streamlit run ui_app.py

env_variables:
  STREAMLIT_SERVER_PORT: 8080
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_SERVER_ENABLECORS: false

handlers:
- url: /
  script: auto
