# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.speak_v1text_type import SpeakV1TextType


class SpeakV1TextParams(typing_extensions.TypedDict):
    type: SpeakV1TextType
    """
    Message type identifier
    """

    text: str
    """
    The input text to be converted to speech
    """
