# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.speak_v1warning_type import SpeakV1WarningType


class SpeakV1WarningParams(typing_extensions.TypedDict):
    type: SpeakV1WarningType
    """
    Message type identifier
    """

    description: str
    """
    A description of what went wrong
    """

    code: str
    """
    Error code identifying the type of error
    """
