# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ListenV1UtteranceEndParams(typing_extensions.TypedDict):
    type: typing.Literal["UtteranceEnd"]
    """
    Message type identifier
    """

    channel: typing.Sequence[float]
    """
    The channel
    """

    last_word_end: float
    """
    The last word end
    """
