# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ListenV1CloseStream,
        ListenV1CloseStreamType,
        ListenV1Finalize,
        ListenV1FinalizeType,
        ListenV1KeepAlive,
        ListenV1KeepAliveType,
        ListenV1Metadata,
        ListenV1Results,
        ListenV1ResultsChannel,
        ListenV1ResultsChannelAlternativesItem,
        ListenV1ResultsChannelAlternativesItemWordsItem,
        ListenV1ResultsEntitiesItem,
        ListenV1ResultsMetadata,
        ListenV1ResultsMetadataModelInfo,
        ListenV1SpeechStarted,
        ListenV1UtteranceEnd,
    )
    from . import media
    from .media import (
        MediaTranscribeRequestCallbackMethod,
        MediaTranscribeRequestCustomIntentMode,
        MediaTranscribeRequestCustomTopicMode,
        MediaTranscribeRequestEncoding,
        MediaTranscribeRequestModel,
        MediaTranscribeRequestSummarize,
        MediaTranscribeRequestVersion,
        MediaTranscribeResponse,
        MediaTranscribeResponseParams,
    )
    from .requests import (
        ListenV1CloseStreamParams,
        ListenV1FinalizeParams,
        ListenV1KeepAliveParams,
        ListenV1MetadataParams,
        ListenV1ResultsChannelAlternativesItemParams,
        ListenV1ResultsChannelAlternativesItemWordsItemParams,
        ListenV1ResultsChannelParams,
        ListenV1ResultsEntitiesItemParams,
        ListenV1ResultsMetadataModelInfoParams,
        ListenV1ResultsMetadataParams,
        ListenV1ResultsParams,
        ListenV1SpeechStartedParams,
        ListenV1UtteranceEndParams,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "ListenV1CloseStream": ".types",
    "ListenV1CloseStreamParams": ".requests",
    "ListenV1CloseStreamType": ".types",
    "ListenV1Finalize": ".types",
    "ListenV1FinalizeParams": ".requests",
    "ListenV1FinalizeType": ".types",
    "ListenV1KeepAlive": ".types",
    "ListenV1KeepAliveParams": ".requests",
    "ListenV1KeepAliveType": ".types",
    "ListenV1Metadata": ".types",
    "ListenV1MetadataParams": ".requests",
    "ListenV1Results": ".types",
    "ListenV1ResultsChannel": ".types",
    "ListenV1ResultsChannelAlternativesItem": ".types",
    "ListenV1ResultsChannelAlternativesItemParams": ".requests",
    "ListenV1ResultsChannelAlternativesItemWordsItem": ".types",
    "ListenV1ResultsChannelAlternativesItemWordsItemParams": ".requests",
    "ListenV1ResultsChannelParams": ".requests",
    "ListenV1ResultsEntitiesItem": ".types",
    "ListenV1ResultsEntitiesItemParams": ".requests",
    "ListenV1ResultsMetadata": ".types",
    "ListenV1ResultsMetadataModelInfo": ".types",
    "ListenV1ResultsMetadataModelInfoParams": ".requests",
    "ListenV1ResultsMetadataParams": ".requests",
    "ListenV1ResultsParams": ".requests",
    "ListenV1SpeechStarted": ".types",
    "ListenV1SpeechStartedParams": ".requests",
    "ListenV1UtteranceEnd": ".types",
    "ListenV1UtteranceEndParams": ".requests",
    "MediaTranscribeRequestCallbackMethod": ".media",
    "MediaTranscribeRequestCustomIntentMode": ".media",
    "MediaTranscribeRequestCustomTopicMode": ".media",
    "MediaTranscribeRequestEncoding": ".media",
    "MediaTranscribeRequestModel": ".media",
    "MediaTranscribeRequestSummarize": ".media",
    "MediaTranscribeRequestVersion": ".media",
    "MediaTranscribeResponse": ".media",
    "MediaTranscribeResponseParams": ".media",
    "media": ".media",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ListenV1CloseStream",
    "ListenV1CloseStreamParams",
    "ListenV1CloseStreamType",
    "ListenV1Finalize",
    "ListenV1FinalizeParams",
    "ListenV1FinalizeType",
    "ListenV1KeepAlive",
    "ListenV1KeepAliveParams",
    "ListenV1KeepAliveType",
    "ListenV1Metadata",
    "ListenV1MetadataParams",
    "ListenV1Results",
    "ListenV1ResultsChannel",
    "ListenV1ResultsChannelAlternativesItem",
    "ListenV1ResultsChannelAlternativesItemParams",
    "ListenV1ResultsChannelAlternativesItemWordsItem",
    "ListenV1ResultsChannelAlternativesItemWordsItemParams",
    "ListenV1ResultsChannelParams",
    "ListenV1ResultsEntitiesItem",
    "ListenV1ResultsEntitiesItemParams",
    "ListenV1ResultsMetadata",
    "ListenV1ResultsMetadataModelInfo",
    "ListenV1ResultsMetadataModelInfoParams",
    "ListenV1ResultsMetadataParams",
    "ListenV1ResultsParams",
    "ListenV1SpeechStarted",
    "ListenV1SpeechStartedParams",
    "ListenV1UtteranceEnd",
    "ListenV1UtteranceEndParams",
    "MediaTranscribeRequestCallbackMethod",
    "MediaTranscribeRequestCustomIntentMode",
    "MediaTranscribeRequestCustomTopicMode",
    "MediaTranscribeRequestEncoding",
    "MediaTranscribeRequestModel",
    "MediaTranscribeRequestSummarize",
    "MediaTranscribeRequestVersion",
    "MediaTranscribeResponse",
    "MediaTranscribeResponseParams",
    "media",
]
