# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class SpeakV2SpeechInterruptedMetadataControlsAppliedParams(typing_extensions.TypedDict):
    """
    Counts of the inline controls the server acted on during the turn. A control that was rejected or ignored is reported through a `Warning` and does not count here.
    """

    pronunciations_applied: int
    """
    Pronunciation overrides successfully applied. Mirrors the Aura-2 `dg-pronunciations-applied` REST header.
    """

    breaks_applied: int
    """
    Pause (break) controls successfully applied. Mirrors the Aura-2 `dg-breaks-applied` REST header. A pause whose duration was out of range or off the supported increment is stripped rather than applied, so it is excluded from this count.
    """

    pronunciation_warnings: int
    """
    Pronunciation entries that triggered a warning (invalid IPA, word too long). Mirrors the Aura-2 `dg-pronunciation-warnings` REST header.
    """
