# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .speak_v2configure_success_applied import SpeakV2ConfigureSuccessAppliedParams


class SpeakV2ConfigureSuccessParams(typing_extensions.TypedDict):
    type: typing.Literal["ConfigureSuccess"]
    """
    Message type identifier
    """

    applied: SpeakV2ConfigureSuccessAppliedParams
    """
    Synthesis configuration. A field is present only when it has been set on this session.
    """
