# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class SpeakV2WarningParams(typing_extensions.TypedDict):
    type: typing.Literal["Warning"]
    """
    Message type identifier
    """

    code: str
    """
    Warning code identifying the condition, in `SCREAMING_SNAKE_CASE`. Early Access codes are `NO_ACTIVE_SPEECH` (a speech-scoped message arrived with no active turn) and `SYNTHESIS_RETRYING` (a synthesis request failed and is being retried).
    """

    description: str
    """
    A human-readable description of the warning
    """
