# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .speak_v2interrupt_playback_offset import SpeakV2InterruptPlaybackOffsetParams


class SpeakV2InterruptParams(typing_extensions.TypedDict):
    type: typing.Literal["Interrupt"]
    """
    Message type identifier
    """

    playback_offset: typing_extensions.NotRequired[SpeakV2InterruptPlaybackOffsetParams]
    """
    How much audio the client had played when the user barged in. Optional: without it the server cannot split the turn's text, so `SpeechInterrupted` omits `text_spoken` and `text_remaining`.
    
    The offset is cumulative from the start of the *session*, not from the start of the current turn. Each `Interrupt` must advance past the position the previous one established.
    """
