# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class SpeakV2SpeakParams(typing_extensions.TypedDict):
    type: typing.Literal["Speak"]
    """
    Message type identifier
    """

    text: str
    """
    The input text to synthesize
    """
