name: "🐛 Bug report"
description: Report something that is broken or crashes
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please give a **minimal** repro when you can.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short one-liner of the problem
      placeholder: "Crash when calling client.listen.v2 from a thread"
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Tell us what you saw and what you expected instead
      placeholder: |
        Actual:
        - …

        Expected:
        - …
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      description: Numbered steps; include inputs that matter (model, options, etc.)
      placeholder: |
        1. Install deepgram-sdk==5.0.0
        2. Run the code below
        3. Observe error XYZ
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal code sample
      description: Small, runnable example (trim secrets). Attach a gist/repo if easier.
      render: python
      placeholder: |
        from deepgram import Deepgram
        # minimal snippet here
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / traceback
      description: Full stack trace or error message (best with DEBUG logs)
      render: text
      placeholder: |
        Traceback (most recent call last):
        ...
    validations:
      required: false

  - type: dropdown
    id: transport
    attributes:
      label: Transport
      options:
        - HTTP
        - WebSocket
        - Both / Not sure
    validations:
      required: true

  - type: input
    id: endpoint
    attributes:
      label: API endpoint / path
      placeholder: "/v1/listen/…  or  /v1/speak/…"
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model(s) used
      placeholder: "nova-2, aura-asteria-en, etc."
    validations:
      required: false

  - type: dropdown
    id: repro_rate
    attributes:
      label: How often?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Only once
    validations:
      required: true

  - type: checkboxes
    id: regression
    attributes:
      label: Is this a regression?
      options:
        - label: "Yes, it worked in an earlier version"
          required: false

  - type: input
    id: worked_version
    attributes:
      label: Last working SDK version (if known)
      placeholder: "4.8.1"
    validations:
      required: false

  - type: input
    id: sdk_version
    attributes:
      label: SDK version
      placeholder: "5.0.0"
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: "3.10.14"
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Install method
      options:
        - pip
        - pipx
        - Poetry
        - uv
        - Conda
        - From source
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: OS
      multiple: true
      options:
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (x86_64)
        - Linux (arm64)
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: extra_env
    attributes:
      label: Environment details
      description: Anything else? Docker, Fly.io, proxies, corporate network, etc.
      render: text
    validations:
      required: false

  - type: input
    id: repro_repo
    attributes:
      label: Link to minimal repro (optional)
      placeholder: "https://github.com/yourname/repro"
    validations:
      required: false

  - type: input
    id: session_id
    attributes:
      label: Session ID (optional)
      placeholder: "123e4567-e89b-12d3-a456-426614174000"
    validations:
      required: false

  - type: input
    id: project_id
    attributes:
      label: Project ID (optional)
      placeholder: "proj_abc123"
    validations:
      required: false

  - type: input
    id: request_id
    attributes:
      label: Request ID (optional)
      description: From API error messages or response headers (`x-dg-request-id`)
      placeholder: "req_def456"
    validations:
      required: false

  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project’s Code of Conduct
          required: true
