# This file was auto-generated by Fern from our API Definition.

import typing

SpeakV2ConfigureFailureCode = typing.Union[
    typing.Literal["SPEED_OUT_OF_RANGE", "SPEED_INCREMENT_INVALID", "SPEED_NOT_SUPPORTED", "INTERNAL_ERROR"], typing.Any
]
