# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel


class SpeakV2SessionMetadata(UncheckedBaseModel):
    type: typing.Literal["SessionMetadata"] = pydantic.Field(default="SessionMetadata")
    """
    Message type identifier
    """

    total_audio_duration_ms: int = pydantic.Field()
    """
    Cumulative audio duration produced across the session, in milliseconds
    """

    total_input_character_count: int = pydantic.Field()
    """
    Cumulative raw input character count across the session
    """

    total_billable_character_count: int = pydantic.Field()
    """
    Cumulative billable character count across the session
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
