# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .speak_v2speech_interrupted_metadata import SpeakV2SpeechInterruptedMetadata


class SpeakV2SpeechInterrupted(UncheckedBaseModel):
    type: typing.Literal["SpeechInterrupted"] = pydantic.Field(default="SpeechInterrupted")
    """
    Message type identifier
    """

    audio_played_ms: int = pydantic.Field()
    """
    How much audio the client had played when the interrupt landed, in milliseconds from the start of the session. Echoes the `Interrupt`'s `playback_offset` when one was supplied. Otherwise it is the server's own total, representing the audio that has been generated so far. A client that sends its first `Interrupt` without an offset can use this value as the baseline the next one must advance past.
    """

    text_spoken: typing.Optional[str] = pydantic.Field(default=None)
    """
    The portion of the turn's text the user heard. Omitted when the `Interrupt` carried no `playback_offset`.
    """

    text_remaining: typing.Optional[str] = pydantic.Field(default=None)
    """
    The portion of the turn's text the user did not hear. Omitted when the `Interrupt` carried no `playback_offset`.
    """

    metadata: SpeakV2SpeechInterruptedMetadata = pydantic.Field()
    """
    Billing and timing for a single turn.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
