# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions


class AgentVariableV1Params(typing_extensions.TypedDict):
    """
    A template variable for agent configurations
    """

    variable_id: str
    """
    The unique identifier of the variable
    """

    key: str
    """
    The variable name, following the DG_<VARIABLE_NAME> format
    """

    value: typing.Any
    created_at: typing_extensions.NotRequired[dt.datetime]
    """
    Timestamp when the variable was created
    """

    updated_at: typing_extensions.NotRequired[dt.datetime]
    """
    Timestamp when the variable was last updated
    """
