# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.agent_think_models_v1response_models_item_zero_id import AgentThinkModelsV1ResponseModelsItemZeroId
from ..types.agent_think_models_v1response_models_item_zero_provider import (
    AgentThinkModelsV1ResponseModelsItemZeroProvider,
)


class AgentThinkModelsV1ResponseModelsItemZeroParams(typing_extensions.TypedDict):
    """
    OpenAI models
    """

    id: AgentThinkModelsV1ResponseModelsItemZeroId
    """
    The unique identifier of the OpenAI model
    """

    name: str
    """
    The display name of the model
    """

    provider: AgentThinkModelsV1ResponseModelsItemZeroProvider
    """
    The provider of the model
    """
