# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.cartesia_model_id import CartesiaModelId
from .cartesia_voice import CartesiaVoiceParams


class CartesiaParams(typing_extensions.TypedDict):
    type: typing.Literal["cartesia"]
    version: typing_extensions.NotRequired[typing.Literal["2025-03-17"]]
    """
    The API version header for the Cartesia text-to-speech API
    """

    model_id: CartesiaModelId
    """
    Cartesia model ID
    """

    voice: CartesiaVoiceParams
    language: typing_extensions.NotRequired[str]
    """
    Cartesia language code
    """

    volume: typing_extensions.NotRequired[float]
    """
    Volume level for Cartesia TTS output. Valid range: 0.5 to 2.0. See [Cartesia documentation](https://docs.cartesia.ai/build-with-cartesia/sonic-3/volume-speed-emotion#volume-speed-and-emotion).
    """
