# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class DeepgramListenProviderV2Params(typing_extensions.TypedDict):
    type: typing.Literal["deepgram"]
    """
    Provider type for speech-to-text
    """

    version: typing_extensions.NotRequired[typing.Literal["v2"]]
    """
    Specifies usage of the V2 Deepgram speech-to-text API (e.g. Flux)
    """

    model: str
    """
    Model to use for speech to text using the V2 API (e.g. flux-general-en, flux-general-multi)
    """

    language_hints: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    An array of one or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details.
    """

    eot_threshold: typing_extensions.NotRequired[float]
    """
    End-of-turn confidence required to finish a turn. Valid range: 0.5 - 1.0. Defaults to 0.7. Set to 1.0 to fully suppress natural end-of-turn detection and end turns with the ForceEndTurn message.
    """

    eager_eot_threshold: typing_extensions.NotRequired[float]
    """
    End-of-turn confidence required to fire an eager end-of-turn event. When set, enables EagerEndOfTurn and TurnResumed events. Valid range: 0.3 - 0.9.
    """

    eot_timeout_ms: typing_extensions.NotRequired[int]
    """
    A turn will be finished when this much time in milliseconds has passed after speech, regardless of EOT confidence. Defaults to 5000.
    """

    keyterms: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Prompt keyterm recognition to improve Keyword Recall Rate
    """
