# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ListProjectMembersV1ResponseMembersItemParams(typing_extensions.TypedDict):
    member_id: typing_extensions.NotRequired[str]
    """
    The unique identifier of the member
    """

    scopes: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    The API scopes of the member
    """

    email: typing_extensions.NotRequired[str]
    first_name: typing_extensions.NotRequired[str]
    last_name: typing_extensions.NotRequired[str]
