# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .shared_intents_results import SharedIntentsResultsParams


class SharedIntentsParams(typing_extensions.TypedDict):
    """
    Output whenever `intents=true` is used
    """

    results: typing_extensions.NotRequired[SharedIntentsResultsParams]
