# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel


class ListenV1Configure(UncheckedBaseModel):
    type: typing.Literal["Configure"] = pydantic.Field(default="Configure")
    """
    Message type identifier
    """

    keyterms: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Replaces the stream's keyterms. Compatible with all Nova-3 models, monolingual and multilingual; on other
    models the server returns an `Error` with code `KeytermsNotSupported`. Each array replaces the entire list,
    including keyterms set with the `keyterm` query parameter. Send an empty array to clear all keyterms. Omit
    the field, or set it to `null`, to keep the current keyterms.
    
    Each entry is a plain term or phrase with no weights or intensifiers. The 500-token keyterm limit that
    applies to the `keyterm` query parameter also applies to each update. An over-limit update returns an
    `Error`, and the stream keeps its previous keyterms.
    """

    features: typing.Optional[typing.Dict[str, bool]] = pydantic.Field(default=None)
    """
    Turns formatting features on or off. Each key is a feature name and each value is a boolean, for
    example `{"numerals": true}`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
