# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel


class ListenV1ResultsMetadataDiarizeInfo(UncheckedBaseModel):
    """
    The diarizer that produced the speaker labels. Present only when a diarizer ran.
    """

    model_uuid: str = pydantic.Field()
    """
    The diarizer model UUID
    """

    arch: str = pydantic.Field()
    """
    The diarizer arch, such as `v1` or `v2`
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
