# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .listen_v1speech_started_type import ListenV1SpeechStartedType


class ListenV1SpeechStarted(UncheckedBaseModel):
    type: ListenV1SpeechStartedType = pydantic.Field()
    """
    Message type identifier
    """

    channel: typing.List[float] = pydantic.Field()
    """
    The channel
    """

    timestamp: float = pydantic.Field()
    """
    The timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
