# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ....requests.listen_v2keyterm import ListenV2KeytermParams
from .listen_v2configure_thresholds import ListenV2ConfigureThresholdsParams


class ListenV2ConfigureParams(typing_extensions.TypedDict):
    type: typing.Literal["Configure"]
    """
    Message type identifier
    """

    thresholds: typing_extensions.NotRequired[ListenV2ConfigureThresholdsParams]
    """
    Updates each parameter, if it is supplied. If a particular threshold parameter 
    is not supplied, the configuration continues using the currently configured value.
    """

    keyterms: typing_extensions.NotRequired[ListenV2KeytermParams]
