# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.listen_v2close_stream_type import ListenV2CloseStreamType


class ListenV2CloseStreamParams(typing_extensions.TypedDict):
    type: ListenV2CloseStreamType
    """
    Message type identifier
    """
