# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ....requests.listen_v2keyterm import ListenV2KeytermParams
from .listen_v2configure_success_thresholds import ListenV2ConfigureSuccessThresholdsParams


class ListenV2ConfigureSuccessParams(typing_extensions.TypedDict):
    type: typing.Literal["ConfigureSuccess"]
    """
    Message type identifier
    """

    request_id: str
    """
    The unique identifier of the request
    """

    thresholds: ListenV2ConfigureSuccessThresholdsParams
    """
    Updates each parameter, if it is supplied. If a particular threshold parameter 
    is not supplied, the configuration continues using the currently configured value.
    """

    keyterms: ListenV2KeytermParams
    sequence_id: float
    """
    Starts at `0` and increments for each message the server sends
    to the client.  This includes messages of other types, like
    `TurnInfo` messages.
    """
