from .conftest import get_client, verify_request_count


def test_manage_v1_projects_usage_breakdown_get() -> None:
    """Test get endpoint with WireMock"""
    test_id = "manage.v1.projects.usage.breakdown.get.0"
    client = get_client(test_id)
    client.manage.v1.projects.usage.breakdown.get(
        project_id="123456-7890-1234-5678-901234",
        start="start",
        end="end",
        grouping="accessor",
        accessor="12345678-1234-1234-1234-123456789012",
        alternatives=True,
        callback_method=True,
        callback=True,
        channels=True,
        custom_intent_mode=True,
        custom_intent=True,
        custom_topic_mode=True,
        custom_topic=True,
        deployment="hosted",
        detect_entities=True,
        detect_language=True,
        diarize=True,
        dictation=True,
        encoding=True,
        endpoint="listen",
        extra=True,
        filler_words=True,
        intents=True,
        keyterm=True,
        keywords=True,
        language=True,
        measurements=True,
        method="sync",
        model="6f548761-c9c0-429a-9315-11a1d28499c8",
        multichannel=True,
        numerals=True,
        paragraphs=True,
        profanity_filter=True,
        punctuate=True,
        redact=True,
        replace=True,
        sample_rate=True,
        search=True,
        sentiment=True,
        smart_format=True,
        summarize=True,
        tag="tag1",
        topics=True,
        utt_split=True,
        utterances=True,
        version=True,
    )
    verify_request_count(
        test_id,
        "GET",
        "/v1/projects/123456-7890-1234-5678-901234/usage/breakdown",
        {
            "start": "start",
            "end": "end",
            "grouping": "accessor",
            "accessor": "12345678-1234-1234-1234-123456789012",
            "alternatives": "true",
            "callback_method": "true",
            "callback": "true",
            "channels": "true",
            "custom_intent_mode": "true",
            "custom_intent": "true",
            "custom_topic_mode": "true",
            "custom_topic": "true",
            "deployment": "hosted",
            "detect_entities": "true",
            "detect_language": "true",
            "diarize": "true",
            "dictation": "true",
            "encoding": "true",
            "endpoint": "listen",
            "extra": "true",
            "filler_words": "true",
            "intents": "true",
            "keyterm": "true",
            "keywords": "true",
            "language": "true",
            "measurements": "true",
            "method": "sync",
            "model": "6f548761-c9c0-429a-9315-11a1d28499c8",
            "multichannel": "true",
            "numerals": "true",
            "paragraphs": "true",
            "profanity_filter": "true",
            "punctuate": "true",
            "redact": "true",
            "replace": "true",
            "sample_rate": "true",
            "search": "true",
            "sentiment": "true",
            "smart_format": "true",
            "summarize": "true",
            "tag": "tag1",
            "topics": "true",
            "utt_split": "true",
            "utterances": "true",
            "version": "true",
        },
        1,
    )
