# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentThinkModelsV1ResponseModelsItemId(UniversalBaseModel):
    """
    AWS Bedrock models (custom models accepted)
    """

    id: str = pydantic.Field()
    """
    The unique identifier of the AWS Bedrock model (any model string accepted for BYO LLMs)
    """

    name: str = pydantic.Field()
    """
    The display name of the model
    """

    provider: typing.Literal["aws_bedrock"] = pydantic.Field(default="aws_bedrock")
    """
    The provider of the model
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
