# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class AgentVariableV1(UncheckedBaseModel):
    """
    A template variable for agent configurations
    """

    variable_id: str = pydantic.Field()
    """
    The unique identifier of the variable
    """

    key: str = pydantic.Field()
    """
    The variable name, following the DG_<VARIABLE_NAME> format
    """

    value: typing.Any
    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the variable was created
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the variable was last updated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
