# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .agent_think_models_v1response_models_item_one_id import AgentThinkModelsV1ResponseModelsItemOneId
from .agent_think_models_v1response_models_item_one_provider import AgentThinkModelsV1ResponseModelsItemOneProvider


class AgentThinkModelsV1ResponseModelsItemOne(UncheckedBaseModel):
    """
    Anthropic models
    """

    id: AgentThinkModelsV1ResponseModelsItemOneId = pydantic.Field()
    """
    The unique identifier of the Anthropic model
    """

    name: str = pydantic.Field()
    """
    The display name of the model
    """

    provider: AgentThinkModelsV1ResponseModelsItemOneProvider = pydantic.Field()
    """
    The provider of the model
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
