# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class DeepgramListenProviderV2(UncheckedBaseModel):
    type: typing.Literal["deepgram"] = pydantic.Field(default="deepgram")
    """
    Provider type for speech-to-text
    """

    version: typing.Optional[typing.Literal["v2"]] = pydantic.Field(default=None)
    """
    Specifies usage of the V2 Deepgram speech-to-text API (e.g. Flux)
    """

    model: str = pydantic.Field()
    """
    Model to use for speech to text using the V2 API (e.g. flux-general-en, flux-general-multi)
    """

    language_hints: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    An array of one or more BCP-47 language codes to bias the model toward specific languages. Only supported when model is flux-general-multi. Without hints, the model auto-detects the spoken language. See the Language Prompting guide for details.
    """

    eot_threshold: typing.Optional[float] = pydantic.Field(default=None)
    """
    End-of-turn confidence required to finish a turn. Valid range: 0.5 - 0.9. Defaults to 0.7.
    """

    eager_eot_threshold: typing.Optional[float] = pydantic.Field(default=None)
    """
    End-of-turn confidence required to fire an eager end-of-turn event. When set, enables EagerEndOfTurn and TurnResumed events. Valid range: 0.3 - 0.9.
    """

    eot_timeout_ms: typing.Optional[int] = pydantic.Field(default=None)
    """
    A turn will be finished when this much time in milliseconds has passed after speech, regardless of EOT confidence. Defaults to 5000.
    """

    keyterms: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Prompt keyterm recognition to improve Keyword Recall Rate
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
