# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetProjectV1Response(UniversalBaseModel):
    project_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier of the project
    """

    mip_opt_out: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Model Improvement Program opt-out
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the project
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
