# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GrantV1Response(UniversalBaseModel):
    access_token: str = pydantic.Field()
    """
    JSON Web Token (JWT)
    """

    expires_in: typing.Optional[float] = pydantic.Field(default=None)
    """
    Time in seconds until the JWT expires
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
