# This file was auto-generated by Fern from our API Definition.

ListenV2ConfigureNumerals = bool
"""
Numerals converts numbers from written format to numerical format. Applies to transcripts Flux STT sends after it processes the update.
"""
