# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListProjectPurchasesV1ResponseOrdersItem(UniversalBaseModel):
    order_id: typing.Optional[str] = None
    expiration: typing.Optional[dt.datetime] = None
    created: typing.Optional[dt.datetime] = None
    amount: typing.Optional[float] = None
    units: typing.Optional[str] = None
    order_type: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
