# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ListProjectInvitesV1ResponseInvitesItem(UncheckedBaseModel):
    email: typing.Optional[str] = pydantic.Field(default=None)
    """
    The email address of the invitee
    """

    scope: typing.Optional[str] = pydantic.Field(default=None)
    """
    The scope of the invitee
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
