# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .list_project_keys_v1response_api_keys_item import ListProjectKeysV1ResponseApiKeysItem


class ListProjectKeysV1Response(UncheckedBaseModel):
    api_keys: typing.Optional[typing.List[ListProjectKeysV1ResponseApiKeysItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
