# This file was auto-generated by Fern from our API Definition.

# Backward-compat patch (2026-08-18 regen): the generator retyped this from
# `float` to `Union[Literal["0.85"..."1.15"], Any]` -- a string-literal enum.
# That contradicts the actual API contract (a numeric speech-rate multiplier;
# see the sibling `SpeakV2SpeedValue = float` used by the Configure message) and
# silently changed the documented domain of the `speak.v2.connect(speed=...)`
# parameter from numeric to string. Only the `Any` fallback kept `speed=1.05`
# working. Restored to `float` so the connect param stays exactly what it was on
# `main`, mypy-precise (no reliance on `Any`), and consistent with the Configure
# message. Unfreeze when the spec types the connect `speed` as a number.
SpeakV2Speed = float
"""
Speech-rate multiplier. `1.0` is the model's nominal rate; lower is slower. Accepted values run `0.85` to `1.15` in `0.05` increments. A value outside that range is rejected with `SPEED_OUT_OF_RANGE`; a value inside it but off the `0.05` increment with `SPEED_INCREMENT_INVALID`. Models and languages without runtime speed control reject any value with `SPEED_NOT_SUPPORTED`.
"""
