# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from .speak_v1text_type import SpeakV1TextType


class SpeakV1Text(UncheckedBaseModel):
    type: SpeakV1TextType = pydantic.Field()
    """
    Message type identifier
    """

    text: str = pydantic.Field()
    """
    The input text to be converted to speech
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
