# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel


class SpeakV1Metadata(UncheckedBaseModel):
    type: typing.Literal["Metadata"] = pydantic.Field(default="Metadata")
    """
    Message type identifier
    """

    request_id: str = pydantic.Field()
    """
    Unique identifier for the request
    """

    model_name: str = pydantic.Field()
    """
    Name of the model being used
    """

    model_version: str = pydantic.Field()
    """
    Version of the model being used
    """

    model_uuid: str = pydantic.Field()
    """
    Unique identifier for the model
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
