name: Development Releases

on:
    push:
      branches:
        - "!not_activated_on_branches!*"
      tags:
        - "v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Update Version in __init__.py
        run: |
          sed -i 's/0.0.0/${{ github.ref_name }}/g' ./deepgram/__init__.py
          sed -i 's/name = "deepgram-sdk"/name = "deepgram-unstable-sdk"/g' ./pyproject.toml
          sed -i 's/name="deepgram-sdk"/name="deepgram-unstable-sdk"/g' ./setup.py
          
      - name: Install Dependencies
        run: pip install .

      #- name: Run Tests
      #  run: pytest tests/

      - name: Install build
        run: python -m pip install --upgrade build

      - name: Build SDK
        run: python -m build

      - name: Install twine
        run: python -m pip install --upgrade twine

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_DEV_API_TOKEN }}